# Generated by Django 3.2.17 on 2023-02-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230208_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
